# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 095ef1f1b0608c2c9ab735bfeb5f4a22ec7ac2c40b6294b6135cbabfca44abb8780e9c2ec5305d9e2a8d0afff26e05830dbadd4828b0fed16a27406b487d50ef

test:
  secret_key_base: b85f6159f8d6de511f5766184a870f5bb3b86e452aedd9071d53a7f748faf153758a12bf5bbef16e6c9c0bc63bb6be0b2e4fd4deeeeb4c665b08b7650861a9dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
